# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: katalonQA

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: katalonTask@1
  inputs:
    version: '8.6.0'
    executeArgs: '-retry=0 -statusDelay=15 -testSuitePath="Test Suites/Demo1" -apiKey=$(katalon_api_key)'
  
